# Generated by Django 6.0.7 on 2026-09-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('EL', 'Earned Leave'), ('SL', 'Sick Leave'), ('CL', 'Casual Leave')], max_length=10),
        ),
    ]
